# Random Forests Classification

In this notebook, we will develop a random forests classifier using scikit-learn to classify our data according to whether Djokovic won the match or not. In this notebook, we will use scikit-learn as much as possible while still preserving the ability to compare the performance of the random forests model to other the logistic regression and neural networks we have applied to the same task.

## 1. Imports and Data Preparations

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from utils import shuffle_data_df

In [3]:
df = pd.read_csv("../Data/full_data.csv")

In [4]:
df.head()

,Series,Surface,Round,dj_pts,dj_rank,dj_odds,opp_pts,opp_rank,opp_odds,dj_win,age,is_outdoor,is_five_sets,5SMA
0,International,Clay,2nd Round,417,97,5.00,1170,28,1.14,0,18,1,0,1.000000
1,Masters,Hard,1st Round,440,97,3.50,1385,18,1.28,0,18,1,0,0.500000
2,Grand Slam,Hard,1st Round,431,97,2.50,825,43,1.50,1,18,1,1,0.333333
3,Grand Slam,Hard,2nd Round,431,97,3.50,1230,24,1.28,1,18,1,1,0.500000
4,Grand Slam,Hard,3rd Round,431,97,2.75,770,48,1.39,0,18,1,1,0.600000

We will want to make sure that the data is shuffled in the exact same way as in the logistic regression notebook. The shuff_data function has a built in seed value so calling it normally on our data will do the job.

In [5]:
# Shuffling using same seed as log reg notebook
df_shuff = shuffle_data_df(df)

In [6]:
# Extracting features and targets
y = df_shuff['dj_win']
X = df_shuff.iloc[:, df.columns != 'dj_win']

In [7]:
# One hot encoding
enc = OneHotEncoder(sparse_output=False)
enc.fit(X.iloc[:,:3])
X_dummies = pd.DataFrame(
    enc.transform(X.iloc[:, :3]),
    columns=enc.get_feature_names_out(),
    index=X.index,
)
X_oh = pd.concat([X.iloc[:, 3:], X_dummies], axis=1)

In [8]:
# Shuffle = False to ensure continuity with log reg notebook
X_train, X_test, y_train, y_test = train_test_split(
    X_oh, y, test_size=0.2, shuffle=False)

## 2. Fitting Random Forests Model

In [11]:
rf = RandomForestClassifier()

In [12]:
rf.fit(X_train, y_train)

RandomForestClassifier()

In [13]:
y_pred = rf.predict(X_test)

In [14]:
rf.score(X_test, y_test)

0.836

In [15]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.67      0.18      0.28        45
           1       0.84      0.98      0.91       205

    accuracy                           0.84       250
   macro avg       0.76      0.58      0.59       250
weighted avg       0.81      0.84      0.79       250

In [16]:
features_1 = pd.DataFrame(rf.feature_importances_, index = X_oh.columns)

In [17]:
features_1

                                  0
dj_pts                     0.108600
dj_rank                    0.049125
dj_odds                    0.146546
opp_pts                    0.122639
opp_rank                   0.111555
opp_odds                   0.132759
age                        0.078131
is_outdoor                 0.012152
is_five_sets               0.012190
5SMA                       0.036504
Series_ATP250              0.008256
Series_ATP500              0.007736
Series_Grand Slam          0.012108
Series_International       0.005285
Series_International Gold  0.004206
Series_Masters             0.008733
Series_Masters 1000        0.013646
Series_Masters Cup         0.004572
Surface_Carpet             0.005823
Surface_Clay               0.016776
Surface_Grass              0.007845
Surface_Hard               0.016320
Round_1st Round            0.004854
Round_2nd Round            0.011555
Round_3rd Round            0.009885
Round_4th Round            0.005893
Round_Quarterfinals        0.012266
Round_Round Robin          0.004678
Round_Semifinals           0.016092
Round_The Final            0.013272

The table above shows the importance of individual features in the classification of the data. We can see that the most important features are dj_pts, dj_odds, opp_pts, opp_rank, opp_odds, and age to a slightly lesser extent. This is all expected since these clearly give good indication of how tough the opponent is, and odds essentially give a bookmaker-calibrated probability of Djokovic winning the match which is already very good signal for the end result of the match. Interestingly, dj_rank is not very important which is probably because he was ranked highly for most of his career, so there is not much signal contained in the differences of his own rank.

## 3. Modified Model

Now we will train a second random forest with some hyperparameters. n_estimators is the number of trees, increasing this will decrease the variance of the prediction, cancelling out individual error in trees and smoothing noise. The criterion parameter is the formula used to decide the best split to take at each node, i.e for all features chosen in the random choice, for all possible split points, the criterion increase/decrease in the criterion of choosing this split is calculated and the optimal one chosen. min_samples_split gives the minimum samples required to split an internal node, once the samples in a node are below this, no more splits will be computed on this node.

In [18]:
# hyperparameters
rf2 = RandomForestClassifier(n_estimators = 1000,
                             criterion = 'gini',
                             min_samples_split = 10,
                             random_state = 42)

In [19]:
rf2.fit(X_train, y_train)

RandomForestClassifier(min_samples_split=10, n_estimators=1000, random_state=42)

In [20]:
y_pred = rf2.predict(X_test)

In [21]:
rf2.score(X_test, y_test)

0.836

In [22]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      0.13      0.23        45
           1       0.84      0.99      0.91       205

    accuracy                           0.84       250
   macro avg       0.79      0.56      0.57       250
weighted avg       0.82      0.84      0.79       250

From the classification report, we can see that the model has good precision, meaning that when it does choose $0$/$1$ it is correct $75$/$84$% of the time. However, the recall gives us an idea of what the model is actually learning. We can see that for the label $1$, the model has a $99$% recall rate, meaning that out of all of the true positives in the data, it catches almost all of them. But, the recall rate for label $0$ is $13$%, which is very low, meaning that out of all $0$ labels in the data, it only catches $13$% of them. This indicates that the model has learnt to just guess "win" most of the time, because Djokovic has a high win rate, meaning doing so will lead to a relatively high accuracy. Guessing "win" most of the time will of course mean you catch most of the true wins, and a small amount of the losses, as the recall indicates. We can see in the support column that there are $205" wins and "45" losses. Hence, just choosing win for every match gives an accuracy of $82$%, which the model already sees as good.

## 4. Handling Class Imbalance

We will now train a random forest with even loss weights for each of the classes. This will encourage the model to actually attempt to predict losses more.

In [23]:
rf3 = RandomForestClassifier(n_estimators = 1000,
                             criterion = 'gini',
                             min_samples_split = 10,
                             random_state = 42,
                             class_weight='balanced')

In [24]:
rf3.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', min_samples_split=10,
                       n_estimators=1000, random_state=42)

In [25]:
features_3 = pd.DataFrame(rf3.feature_importances_, index = X_oh.columns)

In [26]:
features_3

                                  0
dj_pts                     0.099716
dj_rank                    0.041701
dj_odds                    0.182306
opp_pts                    0.127402
opp_rank                   0.100919
opp_odds                   0.166601
age                        0.068020
is_outdoor                 0.009762
is_five_sets               0.014684
5SMA                       0.023958
Series_ATP250              0.009259
Series_ATP500              0.009138
Series_Grand Slam          0.016067
Series_International       0.004463
Series_International Gold  0.002007
Series_Masters             0.009265
Series_Masters 1000        0.008841
Series_Masters Cup         0.003608
Surface_Carpet             0.003924
Surface_Clay               0.010183
Surface_Grass              0.007814
Surface_Hard               0.009365
Round_1st Round            0.010162
Round_2nd Round            0.010580
Round_3rd Round            0.006940
Round_4th Round            0.005956
Round_Quarterfinals        0.011130
Round_Round Robin          0.003355
Round_Semifinals           0.011736
Round_The Final            0.011138

In [27]:
y_pred = rf3.predict(X_test)

In [28]:
rf3.score(X_test, y_test)

0.796

In [29]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.45      0.60      0.51        45
           1       0.91      0.84      0.87       205

    accuracy                           0.80       250
   macro avg       0.68      0.72      0.69       250
weighted avg       0.82      0.80      0.81       250

We can see now that, although the score has decreased, the recall of the losses has improved, meaning that the model is actively trying to catch the losses as well as the wins instead of just guessing win most of the time.

## 5. Discussion

In this notebook, we trained a random forest on the full dataset, including all features. We saw that the model can achieve $\approx 84 \%$ accuracy. This was achieved by the models mainly choosing to predict win, because since Djokovic's win rate is very high the model will seem to do well even though they are just guessing win every time. Due to this, we introduced some class imbalance handling, where we modified the weights for datapoints from the different classes to force the model to attempt to extract loss signal aswell. Although this deceased accuracy from $\approx 84\%$ to $\approx 80\%$, the negative recall (number of losses that the model correctly classified) increased from $\approx 13-18\%$ up to $\approx 60 \%$, a substantial improvement.

The logistic regression and this notebook bring up some interesting points. We saw that the odds are by far the most important feature for classification, since they give a bookmaker-algorithm calculated probability of Djokovic winning the match. These are already well-calibrated and will predict most of the signal in the data, including features that are difficult to engineer like current news (e.g "he tweaked something in practice"). Hence, trying to classify while using the odds as a feature already uses the best possible feature of win and loss indication. When adding further features than just the odds, we are trying to predict the signal that the market missed, which is a difficult task. Furthermore, the model learns that odds are a very good indicator for our classification and contain the most signal by far, so just learns to predict using this. Any of the other features, like age, rank, 5SMA, are given much less importance. The accuracies our model achieve are essentially just a reflection of how good the bookmaker odds are at capturing the signal.

This is also an artefact of the player we have chosen. Djokovic wins most of his matches, and we have seen that some models default to just guessing "win" for every match to attain a relatively good accuracy. The losses he does have are often upsets, and there is not much signal to predict these more random events. Hence, when choosing to pursure hard classification, as we have seen the model almost always just pursues the win rate. The better thing to try and predict may be the probability of winning / losing.